// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALDCvy-HKtBuw0LQUg60ktJxdBlwq7ufM',
    appId: '1:332708097744:web:9daed3f2ffe218f98578d5',
    messagingSenderId: '332708097744',
    projectId: 'property-app-1761c',
    authDomain: 'property-app-1761c.firebaseapp.com',
    storageBucket: 'property-app-1761c.appspot.com',
    measurementId: 'G-V3JNP9KMW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoNaOI3u-CqfEJbfJGrtuISYLe1zTcT68',
    appId: '1:332708097744:android:b16e084509b29e1f8578d5',
    messagingSenderId: '332708097744',
    projectId: 'property-app-1761c',
    storageBucket: 'property-app-1761c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwaBk7MkC44QztBfTuIY1gwgA85PGlDrM',
    appId: '1:332708097744:ios:dd7f16dde2669f198578d5',
    messagingSenderId: '332708097744',
    projectId: 'property-app-1761c',
    storageBucket: 'property-app-1761c.appspot.com',
    androidClientId: '332708097744-mruoiqm1aha9ubn711404chopnq4t3mp.apps.googleusercontent.com',
    iosClientId: '332708097744-6dlejh30pqi2g61ar8al2vpdlla0962c.apps.googleusercontent.com',
    iosBundleId: 'com.property.app.propertyApp',
  );
}
